LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

BASE_PATH:= $(LOCAL_PATH)
PACKAGE_NAMESPACE:= org.openbinder.samples
PACKAGE_LEAF:= ShellService
SRC_FILES:= \
	ShellService.bsh

include $(BUILD_PACKAGE)
