LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

BASE_PATH:= $(LOCAL_PATH)
PACKAGE_NAMESPACE:= org.openbinder.services
PACKAGE_LEAF:= MemoryDealer
SRC_FILES:= \
	Heap.cpp \
	main.cpp

include $(BUILD_PACKAGE)
