xmlBootstrapSources:= \
	xml/BufferSource.cpp \
	xml/Creator.cpp \
	xml/DataSource.cpp \
	xml/ParseContext.cpp \
	xml/ParseXML.cpp \
	xml/StringUtils.cpp \
	xml/Writer.cpp \
	xml/XML2ValueParser.cpp \
	xml/XMLIByteInputSource.cpp \
	xml/XMLOStr.cpp \
	xml/XMLParser.cpp \
	xml/XMLWriter.cpp \
	xml/XMLParserCore.cpp \
	xml/Value2XML.cpp

xmlSources:= \
	xml/BufferSource.cpp \
	xml/Creator.cpp \
	xml/DataSource.cpp \
	xml/ParseContext.cpp \
	xml/ParseXML.cpp \
	xml/StringUtils.cpp \
	xml/Tag.cpp \
	xml/Writer.cpp \
	xml/XML2ValueParser.cpp \
	xml/XMLIByteInputSource.cpp \
	xml/XMLOStr.cpp \
	xml/XMLParser.cpp \
	xml/XMLWriter.cpp \
	xml/XMLParserCore.cpp \
	xml/Value2XML.cpp
