LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

BASE_PATH:= $(LOCAL_PATH)
PACKAGE_NAMESPACE:= org.openbinder.samples
PACKAGE_LEAF:= Component
SRC_FILES:= \
	SampleComponent.cpp \
	main_samplecomponent.cpp

include $(BUILD_PACKAGE)
