storageBootstrapSources= \
	storage/File.cpp

storageSources:= \
	storage/CatalogDelegate.cpp \
	storage/DatumGeneratorInt.cpp \
	storage/File.cpp \
	storage/GenericDatum.cpp \
	storage/GenericIterable.cpp \
	storage/GenericNode.cpp \
	storage/IndexedDataNode.cpp \
	storage/IndexedIterable.cpp \
	storage/IndexedTableNode.cpp \
	storage/MetaDataNode.cpp \
	storage/NodeDelegate.cpp \
	storage/StreamDatum.cpp \
	storage/StructuredNode.cpp \
	storage/ValueDatum.cpp
	
#		storage/VFSFile.cpp
#		BDatabaseStore.cpp
#		SDatabase.cpp
#		IDatabaseTable.cpp
#		DatabaseTable.cpp

storageIDLs := \
	storage/IReferable.idl
