/*
 * Copyright (c) 2005 Palmsource, Inc.
 * 
 * This software is licensed as described in the file LICENSE, which
 * you should have received as part of this distribution. The terms
 * are also available at http://www.openbinder.org/license.html.
 * 
 * This software consists of voluntary contributions made by many
 * individuals. For the exact contribution history, see the revision
 * history and logs, available at http://www.openbinder.org
 */

namespace palmos {
namespace support {

/*	NOTE:
	These interfaces are custom-written for C++.  Look in the C++
	header support/IByteStream.h for the C++ API.
*/

interface IByteInput
{
methods:
	ssize_t Read([out]SValue buffer, size_t size, [optional]uint32_t flags);
}

interface IByteOutput
{
methods:
	ssize_t Write(SValue buffer, size_t size, [optional]uint32_t flags);
				
	status_t Sync();
}

interface IByteSeekable
{
methods:
	off_t Seek(off_t position, uint32_t seek_mode);

properties:
	[readonly]off_t position;
}

} }	// namespace palmos::support