/*
 * Copyright (c) 2005 Palmsource, Inc.
 * 
 * This software is licensed as described in the file LICENSE, which
 * you should have received as part of this distribution. The terms
 * are also available at http://www.openbinder.org/license.html.
 * 
 * This software consists of voluntary contributions made by many
 * individuals. For the exact contribution history, see the revision
 * history and logs, available at http://www.openbinder.org
 */

/*!	@file support/IVirtualMachine.idl
	@ingroup CoreSupportBinder

	@brief Binder virtual machine interface.
*/

namespace palmos {
namespace support {

//!	Virtual machines implement this interface to generate their components.
/*!	@ingroup CoreSupportBinder */
interface IVirtualMachine
{	
	methods:
		void Init();
		IBinder InstantiateComponent(	SValue componentInfo,
										SString component,
										SValue args,
										[optional out]status_t outError);
}

} }	// namespace palmos::support
