LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

BASE_PATH:= $(LOCAL_PATH)
PACKAGE_NAMESPACE:= org.openbinder.tools.commands
PACKAGE_LEAF:= Printf
SRC_FILES:= \
	printf.c \
	PrintfCommand.cpp

#include $(BUILD_PACKAGE)
