LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

BASE_PATH:= $(LOCAL_PATH)
PACKAGE_NAMESPACE:= org.openbinder.tools
PACKAGE_LEAF:= BinderShell
SRC_FILES:= \
	BinderCommands.cpp \
	bsh.cpp \
	CV.cpp \
	Parser.cpp \
	SyntaxTree.cpp \
	Test.cpp \
	vm.cpp

include $(BUILD_PACKAGE)
