LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

BASE_PATH:= $(LOCAL_PATH)
PACKAGE_NAMESPACE:= org.openbinder.kits
PACKAGE_LEAF:= support
SRC_FILES:= \
	SupportComponents.cpp

include $(BUILD_PACKAGE)
