LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

BASE_PATH:= $(LOCAL_PATH)
PACKAGE_NAMESPACE:= org.openbinder.services
PACKAGE_LEAF:= TokenSource
SRC_FILES:= \
	main_token_source.cpp

include $(BUILD_PACKAGE)
