LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

BASE_PATH:= $(LOCAL_PATH)
TARGET_PATH:= $(OUT_SCRIPTS)

SCRIPTS:= \
	setup_env.sh \
	process_wrapper.sh \
	process_wrapper_gdb.sh \
	process_wrapper_gdb.cmds \
	boot_script.bsh \
	user_context.bsh \
	test.bsh

include $(BUILD_SCRIPT)
