LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

BASE_PATH:= $(LOCAL_PATH)
PACKAGE_NAMESPACE:= org.openbinder.samples
PACKAGE_LEAF:= ServiceProcess
SRC_FILES:= \
	Service.cpp \
	ServiceCommand.cpp \
	main_serviceprocess.cpp

include $(BUILD_PACKAGE)
