LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

BASE_PATH:= $(LOCAL_PATH)
PACKAGE_NAMESPACE:= org.openbinder.tools.commands
PACKAGE_LEAF:= BPerf
SRC_FILES:= \
	main.cpp \
	EffectIPC.cpp \
	icache.cpp

include $(BUILD_PACKAGE)
